// Mock data for development - replace with real API calls when database is ready

export const MOCK_CLINICS = [
  {
    id: 1,
    name: 'عيادة الأسنان المتقدمة',
    specialty: 'طب أسنان عام',
    address: 'شارع النيل، الدقي، الجيزة',
    city: 'القاهرة',
    phone: '02-33355555',
    latitude: 30.0444,
    longitude: 31.2357,
    rating: 4.8,
    reviewCount: 125,
  },
  {
    id: 2,
    name: 'مركز طب الأسنان الحديث',
    specialty: 'تقويم أسنان',
    address: 'شارع التحرير، القاهرة',
    city: 'القاهرة',
    phone: '02-27777777',
    latitude: 30.0546,
    longitude: 31.2453,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 3,
    name: 'عيادة دكتور أحمد لطب الأسنان',
    specialty: 'طب أسنان تجميلي',
    address: 'المعادي، القاهرة',
    city: 'القاهرة',
    phone: '02-25555555',
    latitude: 29.9614,
    longitude: 31.3385,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: 4,
    name: 'أكاديمية طب الأسنان',
    specialty: 'زراعة أسنان',
    address: 'وسط البلد، القاهرة',
    city: 'القاهرة',
    phone: '02-23333333',
    latitude: 30.0626,
    longitude: 31.2453,
    rating: 4.7,
    reviewCount: 142,
  },
  {
    id: 5,
    name: 'عيادة النيل لطب الأسنان',
    specialty: 'تنظيف أسنان',
    address: 'قصر النيل، القاهرة',
    city: 'القاهرة',
    phone: '02-29999999',
    latitude: 30.0611,
    longitude: 31.2465,
    rating: 4.5,
    reviewCount: 87,
  },
];

export const MOCK_BRANCHES = [
  {
    id: 1,
    clinicId: 1,
    name: 'فرع الدقي الرئيسي',
    address: 'شارع النيل، الدقي، الجيزة',
    phone: '02-33355555',
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    id: 2,
    clinicId: 1,
    name: 'فرع المهندسين',
    address: 'شارع جيزة، المهندسين',
    phone: '02-37777777',
    latitude: 30.0321,
    longitude: 31.2039,
  },
  {
    id: 3,
    clinicId: 2,
    name: 'الفرع الرئيسي',
    address: 'شارع التحرير، القاهرة',
    phone: '02-27777777',
    latitude: 30.0546,
    longitude: 31.2453,
  },
];

export const MOCK_DOCTORS = [
  {
    id: 1,
    userId: 2,
    clinicId: 1,
    branchId: 1,
    specialization: 'طب أسنان عام',
    licenseNumber: 'LIC001',
    yearsOfExperience: 15,
    user: {
      id: 2,
      name: 'د. محمد علي',
      email: 'dr.ahmed@clinic.com',
      phone: '01001234567',
    },
  },
  {
    id: 2,
    userId: 3,
    clinicId: 1,
    branchId: 1,
    specialization: 'تقويم أسنان',
    licenseNumber: 'LIC002',
    yearsOfExperience: 12,
    user: {
      id: 3,
      name: 'د. فاطمة حسن',
      email: 'dr.fatima@clinic.com',
      phone: '01001234568',
    },
  },
  {
    id: 3,
    userId: 4,
    clinicId: 2,
    branchId: 3,
    specialization: 'تقويم أسنان',
    licenseNumber: 'LIC003',
    yearsOfExperience: 10,
    user: {
      id: 4,
      name: 'د. أحمد سالم',
      email: 'dr.salem@clinic.com',
      phone: '01001234569',
    },
  },
];

export const MOCK_SERVICES = [
  {
    id: 1,
    clinicId: 1,
    name: 'تنظيف الأسنان',
    description: 'تنظيف شامل وتلميع الأسنان',
    price: 150,
    duration: 30,
  },
  {
    id: 2,
    clinicId: 1,
    name: 'حشو الأسنان',
    description: 'حشو التسوس والفراغات',
    price: 300,
    duration: 45,
  },
  {
    id: 3,
    clinicId: 1,
    name: 'خلع الأسنان',
    description: 'خلع آمن للأسنان',
    price: 500,
    duration: 60,
  },
  {
    id: 4,
    clinicId: 2,
    name: 'تقويم الأسنان',
    description: 'تركيب تقويم الأسنان',
    price: 3000,
    duration: 90,
  },
  {
    id: 5,
    clinicId: 2,
    name: 'تنظيف تقويم',
    description: 'تنظيف وصيانة التقويم',
    price: 200,
    duration: 30,
  },
];

export const MOCK_TIME_SLOTS = [
  {
    id: 1,
    branchId: 1,
    doctorId: 1,
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    time: '09:00',
    available: true,
  },
  {
    id: 2,
    branchId: 1,
    doctorId: 1,
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    time: '10:00',
    available: true,
  },
  {
    id: 3,
    branchId: 1,
    doctorId: 1,
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    time: '11:00',
    available: false,
  },
  {
    id: 4,
    branchId: 1,
    doctorId: 1,
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    time: '14:00',
    available: true,
  },
  {
    id: 5,
    branchId: 1,
    doctorId: 1,
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    time: '15:00',
    available: true,
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 1,
    userId: 1,
    clinicId: 1,
    branchId: 1,
    doctorId: 1,
    serviceId: 1,
    appointmentDate: new Date(new Date().getTime() + 3 * 24 * 60 * 60 * 1000),
    appointmentTime: '09:00',
    notes: 'أول زيارة',
    status: 'CONFIRMED',
    createdAt: new Date(),
    clinic: { name: 'عيادة الأسنان المتقدمة' },
    branch: { name: 'فرع الدقي الرئيسي', address: 'شارع النيل، الدقي، الجيزة' },
    doctor: {
      id: 1,
      user: { name: 'د. محمد علي' },
    },
    service: { name: 'تنظيف الأسنان' },
  },
];

export const MOCK_USERS = [
  {
    id: 1,
    name: 'مريض تجريبي',
    email: 'patient@example.com',
    phone: '01001234560',
    role: 'PATIENT',
    createdAt: new Date(),
  },
];
